#!/usr/bin/env bash

# SWWW stuff
images_path=~/.wallpapers/
PICS=($(find "${images_path}" -type f \( -iname \*.jpg -o -iname \*.jpeg -o -iname \*.png -o -iname \*.gif \) | sort))
randomNumber=$((($(date +%s) + RANDOM) + $$))
randomPicture="${PICS[$((randomNumber % ${#PICS[@]}))]}"
wallpaper=$randomPicture
swww img "$wallpaper" --transition-type grow --transition-pos 0.9,0.1 --transition-duration 1.5 --transition-fps 90

# Link current wallpaper
ln -sf "$wallpaper" "$HOME/.current_wallpaper"

./pywal.sh
