theme = "catppuccin_mocha"

[editor]
line-number = "absolute"
cursorline = true
color-modes = true
true-color = true
auto-save = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.statusline]
left = ["mode", "spinner", "file-name", "file-type", "total-line-numbers"]
center = []
right = ["selections", "primary-selection-length", "position", "position-percentage", "spacer", "diagnostics", "workspace-diagnostics", "version-control", "file-line-ending", "file-encoding"]

[editor.indent-guides]
render = true

[editor.lsp]
display-inlay-hints = true

[editor.file-picker]
hidden = false
git-global = false