hl.on("hyprland.start", function()
	hl.exec_cmd("wl-paste --watch cliphist store -max-items 10")
	hl.exec_cmd("~/.config/hypr/waybar-service")
	hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
	hl.exec_cmd("systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
	hl.exec_cmd("/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1")
	hl.exec_cmd("wlsunset -l 55.8 -L 12.06")
	hl.exec_cmd("fcitx5 -d")
	hl.exec_cmd("hyprctl setcursor Bibata-Modern-Classic 24")
	hl.exec_cmd("awww-daemon")
	hl.exec_cmd("deskflow")
	hl.exec_cmd("nm-applet")
	hl.exec_cmd("hypridle")
	hl.exec_cmd("vicinae server")
	hl.exec_cmd("~/.config/hypr/scripts/wall")
end)
