require("modules.common.animations")
require("modules.common.autostart")
require("modules.common.env")
require("modules.common.general")
require("modules.common.keybinds")
require("modules.common.windowrules")
